<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <title>Ticket #{{ $ticket->id }} - {{ $ticket->title }}</title>
    <style>
        @page { margin: 40px; }

        * {
            font-family: 'DejaVu Sans', sans-serif !important;
        }

        body {
            font-size: 11px;
            color: #0f172a;
            line-height: 1.5;
            margin: 0;
            background-color: #ffffff;
        }

        table, tr, td, th {
            font-family: 'DejaVu Sans', sans-serif !important;
            border-collapse: collapse;
        }

        .text-accent { color: {{ $accentColor }}; }

        .header { margin-bottom: 30px; position: relative; }
        .qr-code {
            position: absolute;
            top: 0;
            right: 0;
            border: 1px solid #e2e8f0;
            padding: 5px;
            border-radius: 8px;
        }

        .badge {
            display: inline-block;
            padding: 2px 10px;
            border-radius: 6px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.02em;
        }

        .card {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
            background-color: #ffffff;
        }

        .grid { width: 100%; }
        .grid td { padding: 10px 0; border-bottom: 1px solid #f8fafc; vertical-align: middle; }
        .label { color: #64748b; font-weight: 500; width: 25%; }

        .section-title {
            font-size: 11px;
            font-weight: 800;
            margin: 25px 0 12px;
            display: block;
            border-left: 3px solid {{ $accentColor }};
            padding-left: 10px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #1e293b;
        }

        .comment-item { margin-bottom: 15px; padding-left: 45px; position: relative; }
        .avatar {
            position: absolute;
            left: 0;
            top: 0;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            overflow: hidden;
            background: {{ $accentColor }}15;
            text-align: center;
            line-height: 32px;
        }

        .avatar-img { width: 32px; height: 32px; border-radius: 50%; }
        .avatar-initial { font-weight: bold; color: {{ $accentColor }}; font-size: 12px; }

        .comment-content {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 12px;
            border-radius: 0 12px 12px 12px;
        }
        .comment-user { font-weight: 700; font-size: 11px; color: #0f172a; }
        .comment-date { font-size: 9px; color: #94a3b8; font-weight: 400; margin-left: 5px; }

        .footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9px;
            color: #94a3b8;
            border-top: 1px solid #f1f5f9;
            padding-top: 10px;
        }
    </style>
</head>
<body>

<div class="header">
    <div class="qr-code">
        @if($qrcode)
            <img src="{{ $qrcode }}" width="70" height="70" alt="QR Code">
        @endif
    </div>
    <div style="font-size: 9px; font-weight: 800; margin-bottom: 5px; letter-spacing: 0.1em;" class="text-accent">REPORT • TICKETACK</div>
    <h1 style="font-size: 20px; margin: 0; font-weight: 800; letter-spacing: -0.02em; color: #0f172a;">#{{ $ticket->id }} — {{ $ticket->title }}</h1>
    <div style="margin-top: 5px; color: #64748b; font-size: 10px;">
        {{ __('Generated by') }} <strong style="color: #0f172a">{{ $generatedBy->name }}</strong> {{ __('on') }} {{ now()->format('M d, Y - H:i:s') }}
    </div>
</div>

<div class="card">
    <table class="grid">
        <thead>
        <tr style="display: none;">
            <th scope="col">{{ __('Field') }}</th>
            <th scope="col">{{ __('Value') }}</th>
            <th scope="col">{{ __('Field') }}</th>
            <th scope="col">{{ __('Value') }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row" class="label">{{ __('tickets.column.status') }}</th>
            <td style="font-weight: 600; color: #0f172a;">
                <span style="display: inline-block; width: 6px; height: 6px; border-radius: 50%; background-color: {{ $ticket->status->color }}; margin-right: 4px;"></span>
                {{ $ticket->status->title }}
            </td>
            <th scope="row" class="label">{{ __('tickets.column.priority') }}</th>
            <td>
                    <span class="badge" style="border: 1px solid {{ $ticket->priority->color }}40; color: {{ $ticket->priority->color }}; background: {{ $ticket->priority->color }}08;">
                        {{ $ticket->priority->title }}
                    </span>
            </td>
        </tr>
        <tr>
            <th scope="row" class="label">{{ __('tickets.column.category') }}</th>
            <td style="font-weight: 600; color: #0f172a;">{{ $ticket->category->title }}</td>
            <th scope="row" class="label">{{ __('tickets.filters.equipment') }}</th>
            <td style="font-weight: 600; color: #0f172a;">{{ $ticket->asset->title ?? '—' }}</td>
        </tr>
        <tr>
            <th scope="row" class="label">{{ __('tickets.column.author') }}</th>
            <td style="color: #0f172a;">{{ $ticket->user->name }}</td>
            <th scope="row" class="label">{{ __('tickets.column.assignee') }}</th>
            <td style="color: #0f172a;">{{ $ticket->assignees->map(fn($a) => $a->user->name)->implode(', ') ?: __('tickets.pages.show.tabs.info_content.no_assignees') }}</td>
        </tr>
        </tbody>
    </table>
</div>

<div class="section-title">{{ __('tickets.pages.show.tabs.info_content.description') }}</div>
<div style="background: #ffffff; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; font-size: 11px; white-space: pre-wrap; color: #334155;">{!! e($ticket->description) !!}</div>

<div class="section-title">{{ __('tickets.pages.show.tabs.comments') }}</div>
@forelse($ticket->comments as $comment)
    <div class="comment-item">
        <div class="avatar">
            @if($comment->user->avatar && $comment->user->avatar->url)
                <img src="{{ public_path($comment->user->avatar->url) }}" class="avatar-img" alt="{{ $comment->user->name }}">
            @else
                <span class="avatar-initial">{{ strtoupper(substr($comment->user->name, 0, 1)) }}</span>
            @endif
        </div>
        <div class="comment-content">
            <div class="comment-user">
                {{ $comment->user->name }}
                <span class="comment-date">{{ $comment->created_at->format('M d, Y H:i') }}</span>
            </div>
            <div style="margin-top: 4px; color: #475569;">{{ $comment->content }}</div>
        </div>
    </div>
@empty
    <div style="text-align: center; color: #94a3b8; padding: 25px; border: 1px dashed #e2e8f0; border-radius: 8px;">
        {{ __('tickets.pages.show.tabs.logs_content.no_results') }}
    </div>
@endforelse

<div class="footer">
    {{ __('Document generated by Ticketack.') }}
</div>

</body>
</html>
