name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/ticketack
            
            git pull origin develop
            
            docker compose up -d --build --remove-orphans
            
            docker compose exec -T app composer install --optimize-autoloader --no-dev
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app npm install
            docker compose exec -T app npm run build
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache
            docker compose exec -T app php artisan view:cache
